### ISSUE TITLE
Python was not found, Manage App Execution Aliases

### ISSUE THREAD

**Issue by Nunoma** [Infinitifall/4chv#1]
I downloaded the zip, unpacked it and ran the .bat file as instructed.
It created a folder called `venv_chv`, however, I then get the following error message:
![Screenshot 2024-11-18 131402](https://github.com/user-attachments/assets/0b0ea887-1147-4afd-890b-1494faee8cd3)
I do however have Python 3.12.4 installed, so I don't understand why the installation can't complete.

Any suggestions on what to change?

**Comment by Infinitifall** [comment]
Hello. Yes you have done everything correctly. This could be a Windows specific issue. As per [this](https://stackoverflow.com/a/66409838) you should open Start menu, search for "Manage App Execution Aliases" and turn off "Python". See if this works, report back.
